// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calls.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCallLink = `-- name: CreateCallLink :one
INSERT INTO calls (title,description,call_link,host_id)
VALUES ($1,$2,$3,$4) RETURNING id, title, description, call_link, host_id, created_at, started_at, ended_at, status
`

type CreateCallLinkParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	CallLink    string      `json:"call_link"`
	HostID      uuid.UUID   `json:"host_id"`
}

func (q *Queries) CreateCallLink(ctx context.Context, arg CreateCallLinkParams) (Call, error) {
	row := q.db.QueryRow(ctx, createCallLink,
		arg.Title,
		arg.Description,
		arg.CallLink,
		arg.HostID,
	)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CallLink,
		&i.HostID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const listAllCalls = `-- name: ListAllCalls :many
SELECT id, title, description, call_link, host_id, created_at, started_at, ended_at, status FROM calls
`

func (q *Queries) ListAllCalls(ctx context.Context) ([]Call, error) {
	rows, err := q.db.Query(ctx, listAllCalls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CallLink,
			&i.HostID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCallsByID = `-- name: ListAllCallsByID :many
SELECT id, title, description, call_link, host_id, created_at, started_at, ended_at, status FROM calls WHERE id = $1
`

func (q *Queries) ListAllCallsByID(ctx context.Context, id uuid.UUID) ([]Call, error) {
	rows, err := q.db.Query(ctx, listAllCallsByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CallLink,
			&i.HostID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCall = `-- name: UpdateCall :one
UPDATE calls
SET
title = COALESCE(sql.narg('title'), title),
description = COALESCE(sql.narg('description'), title)
WHERE id = $1
RETURNING id, title, description, call_link, host_id, created_at, started_at, ended_at, status
`

func (q *Queries) UpdateCall(ctx context.Context, id uuid.UUID) (Call, error) {
	row := q.db.QueryRow(ctx, updateCall, id)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CallLink,
		&i.HostID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}
