// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calls.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToCallParticipants = `-- name: AddUserToCallParticipants :one
INSERT INTO call_participants (call_id, user_id)
VALUES ($1, $2) RETURNING id, call_id, user_id, role, joined_at, left_at
`

type AddUserToCallParticipantsParams struct {
	CallID uuid.UUID `json:"call_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddUserToCallParticipants(ctx context.Context, arg AddUserToCallParticipantsParams) (CallParticipant, error) {
	row := q.db.QueryRow(ctx, addUserToCallParticipants, arg.CallID, arg.UserID)
	var i CallParticipant
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const createCallLink = `-- name: CreateCallLink :one
INSERT INTO calls (title,description,call_link,host_id)
VALUES ($1,$2,$3,$4) RETURNING id, title, description, call_link, host_id, created_at, started_at, ended_at, status
`

type CreateCallLinkParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	CallLink    string      `json:"call_link"`
	HostID      uuid.UUID   `json:"host_id"`
}

func (q *Queries) CreateCallLink(ctx context.Context, arg CreateCallLinkParams) (Call, error) {
	row := q.db.QueryRow(ctx, createCallLink,
		arg.Title,
		arg.Description,
		arg.CallLink,
		arg.HostID,
	)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CallLink,
		&i.HostID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const endCall = `-- name: EndCall :one
INSERT INTO call_logs (user_id,call_id,participant,type,time,call_title,duration,participant_count,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, call_id, participant_count, duration, created_at, type, time, call_title, participant, user_id
`

type EndCallParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	CallID           uuid.UUID          `json:"call_id"`
	Participant      pgtype.Text        `json:"participant"`
	Type             pgtype.Text        `json:"type"`
	Time             pgtype.Text        `json:"time"`
	CallTitle        pgtype.Text        `json:"call_title"`
	Duration         string             `json:"duration"`
	ParticipantCount int32              `json:"participant_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) EndCall(ctx context.Context, arg EndCallParams) (CallLog, error) {
	row := q.db.QueryRow(ctx, endCall,
		arg.UserID,
		arg.CallID,
		arg.Participant,
		arg.Type,
		arg.Time,
		arg.CallTitle,
		arg.Duration,
		arg.ParticipantCount,
		arg.CreatedAt,
	)
	var i CallLog
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.ParticipantCount,
		&i.Duration,
		&i.CreatedAt,
		&i.Type,
		&i.Time,
		&i.CallTitle,
		&i.Participant,
		&i.UserID,
	)
	return i, err
}

const getCallByLink = `-- name: GetCallByLink :one
SELECT 
    c.id, c.title, c.description, c.call_link, c.host_id, c.created_at, c.started_at, c.ended_at, c.status,
    u.name as host_name
FROM calls c
JOIN users u ON c.host_id = u.id
WHERE LOWER(c.call_link) = LOWER($1)
`

type GetCallByLinkRow struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CallLink    string             `json:"call_link"`
	HostID      uuid.UUID          `json:"host_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	Status      string             `json:"status"`
	HostName    string             `json:"host_name"`
}

func (q *Queries) GetCallByLink(ctx context.Context, lower string) (GetCallByLinkRow, error) {
	row := q.db.QueryRow(ctx, getCallByLink, lower)
	var i GetCallByLinkRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CallLink,
		&i.HostID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.HostName,
	)
	return i, err
}

const getCallLogsByUserID = `-- name: GetCallLogsByUserID :many
SELECT id, call_id, participant_count, duration, created_at, type, time, call_title, participant, user_id FROM call_logs WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetCallLogsByUserID(ctx context.Context, userID uuid.UUID) ([]CallLog, error) {
	rows, err := q.db.Query(ctx, getCallLogsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CallLog
	for rows.Next() {
		var i CallLog
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.ParticipantCount,
			&i.Duration,
			&i.CreatedAt,
			&i.Type,
			&i.Time,
			&i.CallTitle,
			&i.Participant,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallParticipant = `-- name: GetCallParticipant :one
SELECT id, call_id, user_id, role, joined_at, left_at FROM call_participants WHERE call_id = $1 AND user_id = $2
`

type GetCallParticipantParams struct {
	CallID uuid.UUID `json:"call_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCallParticipant(ctx context.Context, arg GetCallParticipantParams) (CallParticipant, error) {
	row := q.db.QueryRow(ctx, getCallParticipant, arg.CallID, arg.UserID)
	var i CallParticipant
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getHostIDByCallID = `-- name: GetHostIDByCallID :one
SELECT host_id FROM calls WHERE id = $1
`

func (q *Queries) GetHostIDByCallID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getHostIDByCallID, id)
	var host_id uuid.UUID
	err := row.Scan(&host_id)
	return host_id, err
}

const listAllCalls = `-- name: ListAllCalls :many
SELECT id, title, description, call_link, host_id, created_at, started_at, ended_at, status FROM calls
`

func (q *Queries) ListAllCalls(ctx context.Context) ([]Call, error) {
	rows, err := q.db.Query(ctx, listAllCalls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CallLink,
			&i.HostID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCallsByID = `-- name: ListAllCallsByID :many
SELECT id, title, description, call_link, host_id, created_at, started_at, ended_at, status FROM calls WHERE host_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAllCallsByID(ctx context.Context, hostID uuid.UUID) ([]Call, error) {
	rows, err := q.db.Query(ctx, listAllCallsByID, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CallLink,
			&i.HostID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCall = `-- name: UpdateCall :one
UPDATE calls
SET
title = COALESCE(sql.narg('title'), title),
description = COALESCE(sql.narg('description'), title)
WHERE id = $1
RETURNING id, title, description, call_link, host_id, created_at, started_at, ended_at, status
`

func (q *Queries) UpdateCall(ctx context.Context, id uuid.UUID) (Call, error) {
	row := q.db.QueryRow(ctx, updateCall, id)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CallLink,
		&i.HostID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}
