// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Call struct {
	ID        uuid.UUID          `json:"id"`
	HostID    uuid.UUID          `json:"host_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	Status    string             `json:"status"`
}

type CallLog struct {
	ID               uuid.UUID          `json:"id"`
	CallID           uuid.UUID          `json:"call_id"`
	ParticipantCount int32              `json:"participant_count"`
	Duration         int32              `json:"duration"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CallParticipant struct {
	ID       uuid.UUID          `json:"id"`
	CallID   uuid.UUID          `json:"call_id"`
	UserID   uuid.UUID          `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	LeftAt   pgtype.Timestamptz `json:"left_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Avatar    pgtype.Text        `json:"avatar"`
	Bio       pgtype.Text        `json:"bio"`
	Location  pgtype.Text        `json:"location"`
	AppNumber pgtype.Text        `json:"app_number"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
