// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToCallParticipants(ctx context.Context, arg AddUserToCallParticipantsParams) (CallParticipant, error)
	CreateCallLink(ctx context.Context, arg CreateCallLinkParams) (Call, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCallByLink(ctx context.Context, lower string) (GetCallByLinkRow, error)
	GetCallParticipant(ctx context.Context, arg GetCallParticipantParams) (CallParticipant, error)
	GetHostIDByCallID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	ListAllCalls(ctx context.Context) ([]Call, error)
	ListAllCallsByID(ctx context.Context, hostID uuid.UUID) ([]Call, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateCall(ctx context.Context, id uuid.UUID) (Call, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
