// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCallLink(ctx context.Context, arg CreateCallLinkParams) (Call, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	ListAllCalls(ctx context.Context) ([]Call, error)
	ListAllCallsByID(ctx context.Context, id uuid.UUID) ([]Call, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateCall(ctx context.Context, id uuid.UUID) (Call, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
